html_doc_title: LayinPress
html_doc_description: LayinPress - WordPress theme coded in the modern way
html_doc_keywords: layinpress,layin,layout,wordpress,wordpress theme,theme,modern WordPress,www,web page
html_doc_author:
  name: katheroine
  email: katheroine@gmail.com
html_doc_charset: utf-8
html_doc_language: english
html_doc_language_code: en-GB
header_title: LayinPress
header_subtitle: WordPress theme coded in the modern way
footer_copyright_range: 2023
footer_site_name: LayinPress
